### ISSUE TITLE
Add WebComponent template

### ISSUE THREAD

**Issue by FabianWilms** [it-at-m/refarch-templates#5]
The webcomponents starter will reside in the folder `refarch-webcomponent`.

```[tasklist]
### Tasks
- [ ] Add webcomponent specific base project with required dependencies
- [ ] Add simple hello world webcomponent with parameter
- [ ] Add patternlab-vue as default UI component library
- [ ] Include default building process
```

**Comment by devtobi** [comment]
Blocked because there are issues in https://github.com/it-at-m/muc-patternlab-vue that need to be discussed and resolved first.
